url: ssh://git@domain.com:7999/ER/golang-test-deployment.git
mainline: main
generator: helm-deployment-repository
unittest: false
configuration:
    accessKeys:
        - key: SOME_KEY
          permission: REPO_WRITE
        - key: DEPLOYMENT
          permission: REPO_READ
    commitMessageType: DEFAULT
    requireIssue: true
    requireSuccessfulBuilds: 1
    webhooks:
        pipelineTrigger: true
    approvers:
        test-owner-b:
            - somebody
